ALTER DATABASE name RENAME TO new_name;

ALTER DATABASE name OWNER TO {new_owner|CURRENT_ROLE|CURRENT_USER|SESSION_USER}

ALTER DATABASE name SET TABLESPACE new_tablespace;

ALTER DATABASE name RESET ALL;

DROP DATABASE name;